 var albums = [{
	"id": "gqx36",
	"title": "AnimatedGIF",
	"description": null,
	"datetime": 1402212631,
	"cover": "0Q6KORe",
	"cover_width": 500,
	"cover_height": 281,
	"account_url": "kasia99",
	"account_id": 8698073,
	"privacy": "hidden",
	"layout": "blog",
	"views": 16,
	"link": "http://imgur.com/a/gqx36",
	"favorite": false,
	"nsfw": null,
	"section": null,
	"images_count": 37,
	"deletehash": "T31cABHAJk2VCSt",
	"images": [];
}];

var image = [{
		"id": "0Q6KORe",
		"album_id": "gqx36",
		"album": get function() {
			return albums.filter(a=>a.id==this.album_id)[0]
		},
		"title": null,
		"description": null,
		"datetime": 1402212632,
		"type": "image/gif",
		"animated": true,
		"width": 500,
		"height": 281,
		"size": 1708121,
		"views": 106,
		"bandwidth": 181060826,
		"vote": null,
		"favorite": false,
		"nsfw": null,
		"section": null,
		"account_url": null,
		"account_id": null,
		"comment_preview": null,
		"deletehash": "S3gZiBRblH3l8rQ",
		"name": "______cant_sleep",
		"src": {
			"baseurl": get function() { return function(postfix) { if(!postfix) { return "http://imgur.com/" + this.id; } else { return "http://i.imgur.com/" + this.id + postfix; }; } },
			"gifv": this.baseurl(".gifv"),
			"webm": this.baseurl(".webm"),
			"mp4": this.baseurl(".mp4"),
			"link": this.baseurl(".gif")
		},
		"gifv": "http://i.imgur.com/0Q6KORe.gifv",
		"webm": "http://i.imgur.com/0Q6KORe.webm",
		"mp4": "http://i.imgur.com/0Q6KORe.mp4",
		"link": "http://i.imgur.com/0Q6KORe.gif",
		"looping": true
	}]
